[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[project]
name = "cicle-gpx"
version = "0.1.0"
description = "Exploration and visualization of cycling GPX tracks"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "folium>=0.18.0",
    "geopandas>=1.0.1",
    "gpxpy>=1.6.2",
    "ipykernel>=6.29.5",
    "jupyterlab>=4.3.5",
    "matplotlib>=3.9.3",
    "pandas>=2.2.3",
    "pyproj>=3.7.0",
    "shapely>=2.0.6",
]

[tool.setuptools]
packages = []
